import os
import sys
import numpy as np
import pandas as pd


PIPELINE_NAME = "ANnomalyDetectionPipeline"
ARTIFACT_DIR_NAME = "Artifact"
DATA_DIR_NAME = "data"


DATA_UPLOADED_NAME = "UploadedData.csv"
DATA_PROCESSED_NAME = "ProcessedData.csv"
DATA_PROCESS_COMPLETED_NAME = "ValidatedData.csv"
DATA_PROCESS_FAILED_NAME = "InvalidData.csv"
DATA_UPLOADED_DIR_NAME = "Uploaded"
DATA_PROCESSED_DIR_NAME = "Processed"
DATA_PROCESS_COMPLETED_DIR_NAME = "valid_dataset"
DATA_PROCESS_FAILED_DIR_NAME = "invalid_dataset"


DATA_PROCESSING_DIR_NAME = "DataProcessing"
DATA_PREPROCESSING_PIPELINE_OBJ_DIR = "preprocessing_obj"
DATA_PREPROCESSING_PIPELINE_OBJ_NAME = "preprocessing_pipeline.pkl"
DATA_PROCESSING_DATA_TRANSFORM_DIR_NAME = "data_transform"
DATA_PROCESSING_X_TRAIN_TRANSFORM_NAME = "X_train.npy"
DATA_PROCESSING_Y_TRAIN_TRANSFORM_NAME = "y_train.npy"
DATA_PROCESSING_TS_TRANSFORM_NAME = "ts_train.npy"
DATA_PROCESSING_X_TEST_TRANSFORM_NAME = "X_test.npy"
DATA_PROCESSING_Y_TEST_TRANSFORM_NAME = "y_test.npy"
DATA_PROCESSING_TS_TEST_TRANSFORM_NAME = "ts_test.npy"
DATA_PROCESSING_DATALOADER_DIR_NAME = "dataset"
DATA_PROCESSING_TRAIN_DATASET_NAME = "train_loader.pkl"
DATA_PROCESSING_TEST_DATASET_NAME = "test_loader.pkl"
DATA_PROCESSING_TIMESTAMP_DIR_NAME = "timestamp_data"
DATA_PROCESSING_TRAIN_TIMESTAMP_NAME = "train_timestamp.pkl"
DATA_PROCESSING_TEST_TIMESTAMP_NAME = "test_timestamp.pkl"
WINDOW_SIZE = 30            
WINDOW_STEP = 1             
TEST_SPLIT_RATIO = 0.2
BATCH_SIZE = 32
SHUFFLE_TRAIN = True
NUM_WORKERS = 2
PIN_MEMORY = True



